version: 0.0
os: linux
files:
  - source: /target/my-app.war
    destination: /usr/local/apache-tomcat-9.0.37/webapps
hooks:
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 300
      runas: root
